server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/employee
    username: ankush
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: Employee-Service