server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/employee
    username: ankush
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: Employee-Service
    
employee:
  csv:
    header: Title,Full-Name, Gender, Date-Of-Joining, LogonId, Password, Role, EmailId, MobileNo, Permanent-Address, Communication-Address, Alowed-Leaves-In-Month, Carry-Forward(Yes/No), Name-In-Bank, Bank-Name, Branch-Name, Ifsc-Code, Account-Number