server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Employee-Service
    
    
employee:
  csv:
    header: Sno, District, SubDistrict, FromYear, ToYear, FromVolume, ToVolume, FromDoc, ToDoc